version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: house_prices
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  house_price_app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/house_prices"
    ports:
      - "5001:5001"
    volumes:
      - ./zip.zip/House_price_prediction.pkl:/app/zip/House_price_prediction.pkl  # Adjusted for the zip.zip folder
    command: >
      sh -c "sleep 5 && python app.py"

volumes:
  db_data:
